### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by Wilfred**

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks!

I have amended your commit to bump the version strings. Also see https://github.com/magit/magit/wiki/Documentation-tools-and-conventions. I'll add a note about that to the pull request template.

**Comment by tarsius** [comment]
Oh, and you should always use a named feature branch instead of `master`. In Magit you can use `b s` for that after you already started working on `master`. The maintainer can then get the branch using `b y`, amend, and push to your branch using `b p`. Since Github doesn't allow the maintainer to push to the contributors `master` branch, this won't work if you don't use a feature branch. And the result of that is that such pull requests are shown as "closed" instead of as "merged" in Github (and that they forever show commits that weren't merged).

**Comment by Wilfred** [comment]
Thanks, I didn't realise that my choice of branch name had any impact on the maintainer.

If it's of any interest, I avoid `b s` as I don't want to move unpushed commits to a different branch. I have a `b f` command instead: https://emacs.stackexchange.com/a/28527/304

**Comment by npostavs** [comment]
> Since Github doesn't allow the maintainer to push to the contributors master branch,

Worked for me just now in joaotavora/yasnippet#896.

**Comment by tarsius** [comment]
@npostavs Thanks! I will have to look into that. That is likely a recent change.

**Comment by Wilfred** [comment]
It looks like I forgot to allow edits to my branch:

allow_edits

Perhaps that was the source of the problem?

**Comment by tarsius** [comment]
>> Since Github doesn't allow the maintainer to push to the contributors master branch,

> Worked for me just now in joaotavora/yasnippet#896.

Thanks for the notice. I think it used to be the case that this never worked for `master` or at least that the user had to explicitly allow this after creating a pull-request using that branch as source, while for other branches the default setting was used and the default setting is "allow" by, uhm, default.

Currently this is how Magit determines whether the maintainer is allowed to push to the fork:

```lisp
(not (member branch (list .base.ref .base.default_branch)))
```

That's obviously not right, but what else can I do? I don't think that the api provides the necessary information. I even diffed the output for a pr where the maintainer is allowed to push to the fork and when where he is not. I didn't see any difference, beyond different ids and timestamps.

I was not able to change that permission for an existing pr, I always got `You can't perform that action at this time`. But maybe this is because this is an edge case that github doesn't handle properly. I am not only the maintainer of the upstream repository, but also the owner of the fork. Maybe that's also why the api responses don't say whether I am allowed to push - because I am the owner I am always allowed to, so telling me that would be "redundant".

Could someone please fork https://github.com/magit/testibus and open two pull requests. For one keep `Allow edits from maintainers` checked and for the other don't. I will then save and diff the api response for `/repos/magit/testibus/pulls/N`. Once I have done that I will also ask you to toggle the checkbox on these prs.

Or maybe @vermiculus knows how to get the necessary information.

**Comment by tarsius** [comment]
Oh... it's called `maintainer_can_modify`.

**Comment by tarsius** [comment]
And that seems to work as expected.

**Comment by vermiculus** [comment]
^ yup :-) you can also take a look at (I think it's called) magithub-pull-request-new in magithub-pull-request-new.el. Or search that file for 'maintainer'.

**Comment by vermiculus** [comment]
Autocorrect changed the file from magithub-issue-post.el :(

**Pull request closed without merging**
