### PR TITLE
More HTTP errors

### PR DESCRIPTION
**Pull request by vermiculus**

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks. I ended up pushing to separate commits authored by me instead.

> Reduce repetition when [...] signaling HTTP errors

Funny enough I did the same thing yesterday, but it was mixed in with a lot of experimental changes, so there was no separate commit yet. I have created and pushed that now.

> Reduce repetition when defining [...] HTTP errors

I don't understand the appeal of such loops. In my opinion his is more complex, harder to modify *and* more code. So I see absolutely no benefit in this change and at least when defining things, I never do it.  More than just a few people seem to be drawn to this way of "avoiding repetition" but to me it is just a small obfuscation.

> [whitespace]

I fixed that in a separate commit.

**Comment by vermiculus** [comment]
👍, but it looks like 02e9c2594d27a94e85e3fa5fa738a81f35b9ba96 never made it in

**Comment by tarsius** [comment]
I have cherry-picked that now.

**Comment by vermiculus** [comment]
thanks!

**Pull request closed without merging**
