### PR TITLE
manual: Mention case-sensitive match for token creation

### PR DESCRIPTION
**Pull request by Zaeph**
I haven't updated the doc themselves because `make texi` is spitting me an error:
```
Cannot open load file: No such file or directory, ox-extra
make: *** [Makefile:83: texi] Error 255
```
Whilst I figure it out, you can vet the added bit.

### CODE REVIEW

**Comment by Zaeph** [comment]
All right, I should have checked the comment in the `Makefile` first.  Working on it.
https://github.com/magit/ghub/blob/c333f1796399b25784f4b518aefee16907c337e5/Makefile#L74-L79

**Comment by tarsius** [comment]
> You should also verify that the case of your user-name in Emacs matches the one on your forge since the match in @code{~/.authinfo} is case-sensitive.

That's incorrect. Your local username is completely irrelevant.

When you are connecting to a host you haven't connected to before then you are asked `Git variable `github.user' is unset.  Set to: `. You must actively use the user-name with the wrong capitalizing at this point to get into the situation you got yourself into. There are many other errors you might make at this point, including random typos, and I am back to thinking that it would not be appropriate to warn about the one that you happen to have made.

The fact that the variable is `github.user` makes it clear that you are supposed to use your Github user-name, not whatever happens to be your name on the machine you are currently sitting at.

**Comment by Zaeph** [comment]
> That's incorrect. Your local username is completely irrelevant.

I'm sorry for having gotten this wrong and for having wasted your time.

I've retraced my steps to know where I'd erred, and I think this is a XY problem.

1. In the `ghub` prompt for generating a new token, my username appeared as `zaeph`, and after pressing `y` on the `y-or-no-p`, the next prompt was pre-filled with `zaeph`.
screenshot-qEkUFDW3Wn
screenshot-lTxbplxhVA
I'm not sure which variable `ghub` uses to pre-fill that variable.  I've tried renaming my first non-`origin` remote, `zaeph`, to `Zaeph` to see if it changed the prompt, and it didn't.  This is why I assumed that my local name had to do something with it.

2. Even though the API key could get retrieved, my `authinfo.gpg` was not being written to, which forced to manually creating the entry in `authinfo.gpg`.

3. By reading [this page in the manual](https://magit.vc/manual/ghub/How-Ghub-uses-Auth_002dSource.html#How-Ghub-uses-Auth_002dSource), I ended up thinking that I needed to input my **GitHub** username and the name of the package I wanted to access, e.g. `ranger`.  This is the part of the manual that led me to assume this:
> Some Auth-Source backends only support storing three values per entry, the "machine", the "login" and the "password". Because Ghub uses separate tokens for each package, it has to squeeze four values into those three slots, and it does that by using "USERNAME^PACKAGE" as the "login".
>
> **Assuming your username is "ziggy",the package is named "stardust", and you want to access Github.com an entry in one of the three mentioned files would then look like this:**
>
> machine api.github.com login ziggy^stardust password 012345abcdef... [emphasis added]

So, at the end, the line I've manually written in my `authinfo.gpg` was the following:
```
machine api.github.com login Zaeph^ranger password [DATA EXPUNGED]
```

It didn't work.  This is what I had to write to get `ghub` to read my API key from `authinfo.gpg`:
```
machine api.github.com login zaeph^forge password [DATA EXPUNGED]
```

> The fact that the variable is github.user makes it clear that you are supposed to use your Github user-name, not whatever happens to be your name on the machine you are currently sitting at.

That's what I had trouble wrapping my head about.  You are talking about the automatic token retrieval, right?  Then, yes, you'd need to enter the **GitHub** username.  But for storing the token in `authinfo`, am I right to assume that it is *not* your GitHub name that you should write, but your username on your machine?  This is what my tests seem to indicate.

I hope you don't mind me describing this in detail.  I just think there are two problems melded together here, and I'd appreciate if you could take a minute to clarify this.

Thank you.

**Comment by tarsius** [comment]
> By reading [this page in the manual](https://magit.vc/manual/ghub/How-Ghub-uses-
Auth_002dSource.html#How-Ghub-uses-Auth_002dSource), I ended up thinking that I needed to input my **GitHub** username and the name of the package I wanted to access, e.g. `ranger`. 

IMO that's a pretty far fetched conclusion. I don't think many people, including you on a different day, would come to that conclusion. But yes, this is not 100% clear. The reason for that is that there are many things that could go wrong or that a user could misunderstand and a lot of that is *already documented*. But that increased the length of the section `2. Getting Started`. enough to make it necessary to split it into subsections.

The subsection right before the subsection that you are referring to makes it clear that the term "package" refers to "the packages which uses ghub.el to access Github" and not "the repository on Github which we access". We could start documenting all the things in all sections but eventually those sections would be so long themselves that they would have to be split up again and so on. :grinning: 

All your issues steam from that misunderstanding, I think, but here are some other details:
 
* Based on what you have said alone, I think Github might actually accept misspelled usernames. 

* The `Username [for https://zaeph@]:` prompt comes from the `url` package. So much I am sure of, the rest is from memory and I might not remember this 100% correctly. This prompt only appears if things have already gone wrong. It would be better if this prompt would not appear in that case, but it is not possible to keep `url` from doing it.

**Comment by Zaeph** [comment]
> IMO that's a pretty far fetched conclusion. I don't think many people, including you on a different day, would come to that conclusion.

I completely agree.  I'd written #111 on the conclusions I'd gathered the previous day at… 2am.  So I wasn't at my freshest.  I'll make sure to double-check my late-night findings the next time.

> The subsection right before the subsection that you are referring to makes it clear that the term "package" refers to **"the packages which uses ghub.el to access Github" and not "the repository on Github which we access"**.  [emphasis added]

It finally *clicked!*  I was so adamant on getting it working that I jumped from the `forge` manual to the `ghub` manual without thinking about what that entailed.  Now, I agree with you that everything is clear, a little shy of 'crystal' because of the imbrication between `ghub` and `forge` (which makes completely sense on the perspective of modularisation).

>     * Based on what you have said alone, I think Github might actually accept misspelled usernames.

As much as I'd like to ascertain that intuition, I'm probably going to lowercase my username on GitHub to save me further headaches.

>     * The `Username [for https://zaeph@]:` prompt comes from the `url` package. So much I am sure of, the rest is from memory and I might not remember this 100% correctly. **This prompt only appears if things have already gone wrong**. It would be better if this prompt would not appear in that case, but it is not possible to keep `url` from doing it.  [emphasis added]

Judging by the tracker, I'm the only one who's run into that succession of problems, most of which were my fault only.  If something like that does crop up again, I guess we'll know where to start.  For now, I'm just happy to have `forge` working on my system. :)

Thank you for taking the time to come back to me.  I now see that this PR and my original issue were rushed and lacked method.  I'll strive to do better next time.

**Pull request closed without merging**
