### PR TITLE
Explicitly require gnutls

### PR DESCRIPTION
**Pull request by manuel-uberti**
Fixes: https://github.com/magit/forge/issues/149

If you need me to do anything else, feel free to ask.

### CODE REVIEW

**Comment by tarsius** [comment]
I am not sure whether `gnutls.el` is available when `--without-gnutls` was used.

**Comment by manuel-uberti** [comment]
I see. Is there a way to check if Emacs was built with that flag?

**Comment by manuel-uberti** [comment]
Or, to phrase it better: is there a way to check for that flag *without* inspecting `system-configuration-options`? :)

**Comment by manuel-uberti** [comment]
I rebuilt my Emacs with `--without-gnutls`:

```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2019-05-13

Repository revision: d2d4916046e31e46598f0a0edbc65e75b8cb4cc3
Configured using:
--host=x86_64-debian-linux-gnu --with-modules --without-gnutls
```

Now, `forge-pull` results in:
```
Pulling 7bridges-eu/corallo...
Opening TLS connection to ‘api.github.com’...
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 api.github.com’...
Package tls is obsolete!
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 api.github.com’...done
Opening TLS connection to ‘api.github.com’...done
Pulling 7bridges-eu/corallo...done
Storing 7bridges-eu/corallo...done
Running git fetch origin
Git finished
```
But I do see Pull Requests and Issues listed.

**Comment by npostavs** [comment]
> I am not sure whether `gnutls.el` is available when `--without-gnutls` was used.

As far as I know, Emacs never removes `.el` files, regardless of build flags.

**Comment by npostavs** [comment]
> I see. Is there a way to check if Emacs was built with that flag?

Calling `(gnutls-available-p)` will return non-nil if Emacs was built with that flag.

**Comment by manuel-uberti** [comment]
I added the check mentioned by @npostavs. Any further work required?

**Comment by npostavs** [comment]
I think making the require conditional would just cause the  `(void-variable gnutls-algorithm-priority)` error to occur on builds which configure `--without-gnutls`. If this is just about that error, wouldn't it make more sense to just add a couple of `boundp` checks where that variable is used?

**Comment by manuel-uberti** [comment]
The variable `gnutls-algorithm-priority` is only used in `ghub-use-workaround-for-emacs-bug`:
```
(gnutls-algorithm-priority
         (if (and ghub-use-workaround-for-emacs-bug
                  (or (eq ghub-use-workaround-for-emacs-bug 'force)
                      (and (not gnutls-algorithm-priority)
                           (< emacs-major-version 27)
                           (memq (ghub--req-forge req) '(github nil)))))
             "NORMAL:-VERS-TLS1.3"
           gnutls-algorithm-priority))
```
Should I add the checks here?

**Comment by tarsius** [comment]
We need to `require` the library. If libraries are really never removed due to build flags then that's all we need. @manuel-uberti since you have just build using `--without-gnutls`, you can easily check at least for this case.

It the library is missing, then use `(require 'gnutls)` and `(bound-and-true-p gnutls-algorithm-priority)`.

**Comment by manuel-uberti** [comment]
@tarsius If I compile with `--without-gnutls` and use this:
```
(when (not (gnutls-available-p))
  (require 'gnutls))
```
I can use `forge-pull`, and I get:
```
Pulling 7bridges-eu/corallo...
Opening TLS connection to ‘api.github.com’...
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 api.github.com’...
Package tls is obsolete!
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 api.github.com’...done
Opening TLS connection to ‘api.github.com’...done
Pulling 7bridges-eu/corallo...done
Storing 7bridges-eu/corallo...done
Running git fetch origin
Git finished
```

**Comment by manuel-uberti** [comment]
Notice that it works just by requiring `gnutls` too, without the `when`.

**Comment by tarsius** [comment]
> And the library is still there, even though I compiled with ` --without-gnutls`.

Then lets just use `(require 'gnutls)`. Ah, I see you already did that. Merging.

**Comment by tarsius** [comment]
Thanks!

**Comment by manuel-uberti** [comment]
Thanks to you guys for helping figuring this out. :)

**Pull request merged**
